name: Deploy to Dokku

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: grit-web01
    steps:
    - name: Check out code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Cache Ruby Gems
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Install Jekyll and dependencies
      run: |
       bundle config set --local path 'vendor/bundle' # Set the path to install gems locally within the project directory
       bundle install --jobs 4 --verbose # Install dependencies as specified in your Gemfile
  

    - name: Build Jekyll site
      run: bundle exec jekyll build --incremental
      # Ensure this command runs in the directory containing your Jekyll site's source code, if not root.

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -p 22 grit-web02.grit.ucsb.edu >> ~/.ssh/known_hosts
    - name: List built site content
      run: ls -la _site

    - name: Deploy to Dokku
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git remote add dokku dokku@grit-web02.grit.ucsb.edu:michaelides || git remote set-url dokku dokku@grit-web02.grit.ucsb.edu:michaelides
        # Ensure the Git working directory is clean after Jekyll build
        git push dokku +main:main
      working-directory: ./_site
